# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=10)),
                ('division', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
        ),
    ]
